version: '3.9'

services:
 
   keycloak:
    container_name: kc-oidc
    restart: no
    image: quay.io/keycloak/keycloak:23.0.6
    env_file:
      - ./.kc-env
    command:
      - start-dev
    ports:
      - "18080:8080"