server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:18080/realms/nifont
            user-name-attribute: preferred_username

        registration:
          greetings-app-client-credentials:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: greetings-app
            client-secret: aGxGX1SZZOL9HjU0VBwMo2mpH2WRHDau
            scope:
              - greetings

          greetings-app-authorization-code:
            provider: keycloak
            client-id: greetings-app
            client-secret: aGxGX1SZZOL9HjU0VBwMo2mpH2WRHDau
            scope:
              - openid
              - microprofile-jwt